use fusermount3 if available (fuse3)

diff --git a/sshm b/sshm
--- a/sshm
+++ b/sshm
@@ -11,7 +11,7 @@ set -o pipefail; # Catch the error in case mysqldump fails (but gzip succeeds) i
 # Helpers
 
 readonly SCRIPTNAME=$(basename "$0")
-readonly SCRIPTDIR=$(readlink -m "$(dirname "$0")")
+#readonly SCRIPTDIR=$(readlink -m "$(dirname "$0")")
 
 # Options to log output to file (see http://mywiki.wooledge.org/BashFAQ/106)
 #exec >"${SCRIPTNAME}.log" 2>&1
@@ -22,7 +22,7 @@ readonly SCRIPTDIR=$(readlink -m "$(dirname "$0")")
 #
 SSHM_CONFIG_FILE=${SSHM_CONFIG_FILE:-"$HOME/.ssh/sshm_config"}
 SSHM_BASE_MOUNTDIR=${SSHM_BASE_MOUNTDIR:-"$HOME/mnt"}
-SSHM_RMDIR_ON_UNMOUNT=${SSHM_RMDIR_ON_UNMOUNT:-true}
+SSHM_RMDIR_ON_UNMOUNT=${SSHM_RMDIR_ON_UNMOUNT:-false}
 SSHM_MOUNT_OPTIONS=${SSHM_MOUNT_OPTIONS:-"-o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3"}
 
 
@@ -203,7 +203,7 @@ mount_host() {
   fi
   if [ ! -d "$mountpath" ]; then
     log_progress "Creating $mountpath"
-    mkdir "$mountpath" || die "Could not create $mountpath, rc=$?"
+    mkdir -p "$mountpath" || die "Could not create $mountpath, rc=$?"
   fi
   local sshfs_mount_options=$SSHM_MOUNT_OPTIONS
   if [ ${#config[*]} -gt 2 ]; then 
@@ -219,8 +219,12 @@ mount_host() {
 
 _do_unmount_host() {
   local mountpath=$1
-  fusermount -u "$mountpath"
-  check_rc_die $? "Command failed: fusermount -u $mountpath"
+  local fusermount_cmd=fusermount
+  if hash fusermount3; then
+    fusermount_cmd=fusermount3
+  fi
+  $fusermount_cmd -u "$mountpath"
+  check_rc_die $? "Command failed: $fusermount_cmd -u $mountpath"
   log_info "Unmounted: $mountpath" 
   if [ "$SSHM_RMDIR_ON_UNMOUNT" = true ]; then
     rmdir "$mountpath"
